name: Build
on:
  # push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # os: [ debian, ubuntu, alpine, bash, arch, fedora, opensuse, oraclelinux ]
        os: [ gentoo ]
    steps:

    # Reference: https://blog.thesparktree.com/docker-multi-arch-github-actions
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'arm64,arm'
    - name: Set up buildx
      uses: docker/setup-buildx-action@v2

    - name: Checkout & Login
      run: |
        git clone https://github.com/x-cmd/image.git
        docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build ${{ matrix.os }}
      run: cd image && bash .x-cmd/image ${{ matrix.os }}