name: docker build
on:
  # push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Docker build
      run: |
        git clone https://github.com/x-cmd/image.git
        cd image
        docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
        # docker buildx create --use
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx rm builder
        docker buildx create --name builder --driver docker-container --use
        docker buildx inspect --bootstrap

        set +e
        # bash .x-cmd/image alpine
        bash .x-cmd/image debian
        # bash .x-cmd/image ubuntu
        # bash .x-cmd/image centos
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}