name: docker build
on:
  # push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Docker build
      run: |
        git clone https://github.com/x-cmd/image.git
        cd image
        docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
        docker buildx create --use
        bash .x-cmd/image alpine debian ubuntu
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}